[package]
name = "tutorial_example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roqoqo = {version="0.10"}
roqoqo-aqt = {version="0.3", path="../../"}

[workspace]
