name: HQS build and deploy for rust pyo3 repos

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  deploy_cratesio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        # cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
        # cargo publish --manifest-path=roqoqo-aqt/Cargo.toml
        # sleep 45
        # cargo publish --manifest-path=qoqo_aqt/Cargo.toml

# Build macos wheels and upload them to PyPi
  build_maturin_builds_macos:
    name: maturin_build-macos
    needs: deploy_cratesio
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_maturin_macos.yml@main
    with: 
      py_interface_folder: "qoqo_aqt"
      deploy: true
    secrets: inherit

# Build windows wheels and upload them to PyPi
  build_maturin_builds_windows:
    name: maturin_build-windows
    needs: deploy_cratesio
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_maturin_windows.yml@main
    with: 
      py_interface_folder: "qoqo_aqt"
      deploy: true
    secrets: inherit

# Build linux wheels and upload them to PyPi
  manual_build_maturin_builds_linux:
    name: maturin_build-linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: linux wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          manylinux: 2014
          args: --find-interpreter --out wheels -m qoqo_aqt/Cargo.toml --release --locked --zig
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels
